
export interface OfflineQuestion {
  question: string;
  tags: string[];
}

export const OFFLINE_QUESTIONS: OfflineQuestion[] = [
  // --- Frontend Developer ---
  { question: "Explain the difference between `let`, `const`, and `var` in JavaScript.", tags: ['frontend developer', 'javascript', 'engineering'] },
  { question: "What is the purpose of the `useEffect` hook in React? Provide a common use case.", tags: ['frontend developer', 'react', 'engineering'] },
  { question: "Describe the CSS box model.", tags: ['frontend developer', 'css', 'engineering'] },
  { question: "How would you optimize a web page for faster loading?", tags: ['frontend developer', 'performance', 'engineering'] },
  { question: "What is server-side rendering (SSR) and how does it differ from client-side rendering (CSR)?", tags: ['frontend developer', 'react', 'engineering'] },
  { question: "What are React Fragments and why are they useful?", tags: ['frontend developer', 'react', 'engineering'] },
  { question: "Explain the concept of 'lifting state up' in React.", tags: ['frontend developer', 'react', 'engineering'] },
  { question: "What is the difference between `null` and `undefined` in JavaScript?", tags: ['frontend developer', 'javascript', 'engineering'] },
  { question: "How does CSS specificity work?", tags: ['frontend developer', 'css', 'engineering'] },
  { question: "Describe a recent challenging problem you solved while working on a frontend project.", tags: ['frontend developer', 'behavioral', 'engineering'] },
  { question: "What are some new features in ES6 (ECMAScript 2015)?", tags: ['frontend developer', 'javascript', 'engineering'] },
  { question: "How do you handle asynchronous operations in JavaScript using Promises and async/await?", tags: ['frontend developer', 'javascript', 'engineering'] },
  { question: "Explain the role of `webpack` or `Vite` in a modern frontend toolchain.", tags: ['frontend developer', 'tooling', 'engineering'] },
  { question: "What is web accessibility (a11y) and why is it important?", tags: ['frontend developer', 'accessibility', 'engineering'] },
  { question: "Describe how you would implement a responsive design for a complex layout.", tags: ['frontend developer', 'css', 'engineering'] },
  { question: "What is the event loop in JavaScript?", tags: ['frontend developer', 'javascript', 'engineering'] },
  { question: "Explain the concept of closures in JavaScript.", tags: ['frontend developer', 'javascript', 'engineering'] },
  { question: "What is the difference between `==` and `===` in JavaScript?", tags: ['frontend developer', 'javascript', 'engineering'] },

  // --- Backend Engineer ---
  { question: "What is the difference between a SQL and a NoSQL database? Give an example of each.", tags: ['backend engineer', 'database', 'engineering'] },
  { question: "Explain the concept of RESTful APIs. What are the main HTTP verbs used?", tags: ['backend engineer', 'api', 'engineering'] },
  { question: "Describe the request-response cycle in a typical web application.", tags: ['backend engineer', 'architecture', 'engineering'] },
  { question: "How would you secure an API endpoint? Mention at least two methods.", tags: ['backend engineer', 'security', 'engineering'] },
  { question: "What is middleware in the context of a backend framework like Express.js or Django?", tags: ['backend engineer', 'frameworks', 'engineering'] },
  { question: "Explain the purpose of indexing in a database.", tags: ['backend engineer', 'database', 'engineering'] },
  { question: "What is the N+1 query problem and how can you solve it?", tags: ['backend engineer', 'database', 'performance', 'engineering'] },
  { question: "Describe the difference between stateful and stateless applications.", tags: ['backend engineer', 'architecture', 'engineering'] },
  { question: "What are microservices and what are their pros and cons compared to a monolithic architecture?", tags: ['backend engineer', 'architecture', 'engineering'] },
  { question: "How would you handle user authentication and authorization in a web application?", tags: ['backend engineer', 'security', 'engineering'] },
  { question: "Explain caching and describe a common caching strategy.", tags: ['backend engineer', 'performance', 'engineering'] },
  { question: "What is containerization (e.g., Docker) and why is it useful?", tags: ['backend engineer', 'devops', 'engineering'] },
  { question: "Describe a scenario where you would choose GraphQL over REST.", tags: ['backend engineer', 'api', 'engineering'] },
  { question: "What is a message queue (e.g., RabbitMQ, Kafka) and when would you use it?", tags: ['backend engineer', 'architecture', 'engineering'] },
  { question: "How do you manage environment variables in a production application?", tags: ['backend engineer', 'deployment', 'engineering'] },
  { question: "What is database normalization and why is it important?", tags: ['backend engineer', 'database', 'engineering'] },
  { question: "Explain the concept of ACID properties in database transactions.", tags: ['backend engineer', 'database', 'engineering'] },

  // --- Data Scientist ---
  { question: "Explain the difference between supervised and unsupervised machine learning.", tags: ['data scientist', 'ml', 'data science'] },
  { question: "What is overfitting and how can you prevent it?", tags: ['data scientist', 'ml', 'data science'] },
  { question: "Describe a project where you used data to drive a business decision.", tags: ['data scientist', 'business', 'data science'] },
  { question: "You are given a dataset of customer transactions. How would you identify fraudulent transactions?", tags: ['data scientist', 'ml', 'problem solving', 'data science'] },
  { question: "What is a p-value and what does it signify in hypothesis testing?", tags: ['data scientist', 'statistics', 'data science'] },
  { question: "Explain the bias-variance tradeoff in machine learning.", tags: ['data scientist', 'ml', 'data science'] },
  { question: "What is the purpose of a confusion matrix?", tags: ['data scientist', 'ml', 'evaluation', 'data science'] },
  { question: "How would you handle missing data in a dataset?", tags: ['data scientist', 'data cleaning', 'data science'] },
  { question: "Describe the difference between correlation and causation.", tags: ['data scientist', 'statistics', 'data science'] },
  { question: "Which metrics would you use to evaluate a classification model? Why?", tags: ['data scientist', 'ml', 'evaluation', 'data science'] },
  { question: "What are some common data visualization libraries in Python and what are they good for?", tags: ['data scientist', 'python', 'visualization', 'data science'] },
  { question: "Explain what a Random Forest model is and why it might be powerful.", tags: ['data scientist', 'ml', 'data science'] },
  { question: "How would you approach a time-series forecasting problem?", tags: ['data scientist', 'ml', 'data science'] },
  { question: "Describe a situation where you would use logistic regression.", tags: ['data scientist', 'ml', 'data science'] },
  { question: "What is feature engineering and why is it important?", tags: ['data scientist', 'ml', 'data science'] },
  { question: "What is cross-validation and why is it useful?", tags: ['data scientist', 'ml', 'data science'] },
  { question: "Explain Principal Component Analysis (PCA).", tags: ['data scientist', 'ml', 'data science'] },

  // --- Product Manager ---
  { question: "How would you decide which features to build next for a product?", tags: ['product manager', 'prioritization', 'product'] },
  { question: "What is a product roadmap and what should it contain?", tags: ['product manager', 'strategy', 'product'] },
  { question: "Describe how you would conduct user research for a new product idea.", tags: ['product manager', 'research', 'product'] },
  { question: "A key metric for your product has dropped. How would you investigate the cause?", tags: ['product manager', 'analytics', 'product'] },
  { question: "How do you define and measure the success of a product or feature?", tags: ['product manager', 'metrics', 'product'] },
  { question: "Walk me through the process of writing a user story.", tags: ['product manager', 'agile', 'product'] },
  { question: "What is the difference between a product manager and a project manager?", tags: ['product manager', 'roles', 'product'] },
  { question: "How do you say 'no' to a stakeholder's feature request?", tags: ['product manager', 'communication', 'product'] },
  { question: "Describe a product you admire and explain why it's a great product.", tags: ['product manager', 'product sense', 'product'] },
  { question: "What is an A/B test and when would you use one?", tags: ['product manager', 'analytics', 'product'] },
  { question: "How do you work with engineering and design teams?", tags: ['product manager', 'collaboration', 'product'] },
  { question: "What is a Minimum Viable Product (MVP)?", tags: ['product manager', 'strategy', 'product'] },
  { question: "How would you perform a competitive analysis?", tags: ['product manager', 'research', 'product'] },
  { question: "Describe your approach to stakeholder management.", tags: ['product manager', 'communication', 'product'] },
  { question: "What are some of your favorite tools for product management?", tags: ['product manager', 'tools', 'product'] },
  { question: "How do you handle conflict between stakeholders with differing priorities?", tags: ['product manager', 'communication', 'product'] },
  { question: "What is the 'Jobs to be Done' framework?", tags: ['product manager', 'research', 'product'] },

  // --- UI/UX Designer ---
  { question: "Describe your design process from initial concept to final handoff.", tags: ['ui/ux designer', 'process', 'design'] },
  { question: "What is the difference between UI and UX design?", tags: ['ui/ux designer', 'fundamentals', 'design'] },
  { question: "How do you gather and incorporate user feedback into your designs?", tags: ['ui/ux designer', 'research', 'design'] },
  { question: "Explain the importance of a design system. What are its key components?", tags: ['ui/ux designer', 'design systems', 'design'] },
  { question: "Walk me through how you would design a user-friendly login/signup flow.", tags: ['ui/ux designer', 'problem solving', 'design'] },
  { question: "What are some key principles of web accessibility you consider in your designs?", tags: ['ui/ux designer', 'accessibility', 'design'] },
  { question: "What is a user persona and how do you use them in your work?", tags: ['ui/ux designer', 'research', 'design'] },
  { question: "Describe a time you had to balance user needs with business goals.", tags: ['ui/ux designer', 'strategy', 'design'] },
  { question: "What is information architecture and why is it important?", tags: ['ui/ux designer', 'fundamentals', 'design'] },
  { question: "Explain the concept of 'affordance' in UI design.", tags: ['ui/ux designer', 'fundamentals', 'design'] },
  { question: "How do you decide between using a hamburger menu versus a tab bar for mobile navigation?", tags: ['ui/ux designer', 'mobile', 'design'] },
  { question: "What prototyping tools are you familiar with, and which do you prefer? Why?", tags: ['ui/ux designer', 'tools', 'design'] },
  { question: "Describe a design project you are particularly proud of and explain why.", tags: ['ui/ux designer', 'portfolio', 'design'] },
  { question: "How do you collaborate with product managers and developers?", tags: ['ui/ux designer', 'collaboration', 'design'] },
  { question: "What design trends are you currently following?", tags: ['ui/ux designer', 'trends', 'design'] },
  { question: "What are heuristics in usability testing?", tags: ['ui/ux designer', 'research', 'design'] },
  { question: "Explain Fitt's Law and its relevance to UI design.", tags: ['ui/ux designer', 'fundamentals', 'design'] },

  // --- DevOps Engineer ---
  { question: "What is CI/CD and why is it important for software development?", tags: ['devops engineer', 'ci/cd', 'engineering'] },
  { question: "Explain the difference between a container (like Docker) and a virtual machine.", tags: ['devops engineer', 'containers', 'engineering'] },
  { question: "What is Infrastructure as Code (IaC) and what are its benefits? Name a popular IaC tool.", tags: ['devops engineer', 'iac', 'engineering'] },
  { question: "Describe the role of Kubernetes in a modern infrastructure.", tags: ['devops engineer', 'kubernetes', 'engineering'] },
  { question: "How would you monitor a production application for performance and errors?", tags: ['devops engineer', 'monitoring', 'engineering'] },
  { question: "What is a blue-green deployment strategy?", tags: ['devops engineer', 'deployment', 'engineering'] },
  { question: "Explain the purpose of a Dockerfile.", tags: ['devops engineer', 'docker', 'engineering'] },
  { question: "How do you manage secrets (like API keys and database passwords) in a CI/CD pipeline?", tags: ['devops engineer', 'security', 'engineering'] },
  { question: "What is the difference between Git and GitHub?", tags: ['devops engineer', 'git', 'engineering'] },
  { question: "Describe how you would troubleshoot a failing build in a CI pipeline.", tags: ['devops engineer', 'troubleshooting', 'engineering'] },
  { question: "What is configuration management and what tools are used for it (e.g., Ansible, Puppet, Chef)?", tags: ['devops engineer', 'config management', 'engineering'] },
  { question: "Explain the concept of idempotency in the context of configuration management.", tags: ['devops engineer', 'iac', 'engineering'] },
  { question: "How would you set up a basic logging and monitoring stack for a web service?", tags: ['devops engineer', 'monitoring', 'engineering'] },
  { question: "What are the main components of a cloud provider like AWS or GCP that you interact with regularly?", tags: ['devops engineer', 'cloud', 'engineering'] },
  { question: "What is a Git branching strategy you have used and why?", tags: ['devops engineer', 'git', 'engineering'] },
  { question: "What is a Canary release?", tags: ['devops engineer', 'deployment', 'engineering'] },
  { question: "What is the purpose of a `.gitignore` file?", tags: ['devops engineer', 'git', 'engineering'] },
];
